### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by ekkesa** [giuseppecastaldo/ha-addons#1]
Could you please perhaps examples with syntax on the readme and if the message can handle templates.

Thank you!

**Comment by ekkesa** [comment]
Nevermind - Saw it under documentation of the add-on.

How to send to a group is still unclear.

Thx!

**Comment by ekkesa** [comment]
I have tried the following for groups, but it doesn't seem to work. Any suggestions will be appreciated...

```
service: whatsapp.send_message
data:
  clientId: default
  to: KXyCcYkvXSX0X6aX42iX6o@g.us
  body:
    text: Test
```

* Some of the groupID characters have been replaced randomly.
