### ISSUE TITLE
How to send image that's saved on home assistant

### ISSUE THREAD

**Issue by chinedu40** [giuseppecastaldo/ha-addons#16]
I'm trying to make an automation that automatically send a snapshot image. The snapshop is saved in www/tmp/ . what is the format to send this picture that's saved on home assistant?

**Comment by chinedu40** [comment]
For more context, i was using this using the docker image created by @swinster. I figured this out by mapping a volume to the location of the snapshot image on home assistant docker. e.g. ../www/tmp:/snapshots. Then the code to run in the service is

```
service: whatsapp.send_message
data:
  clientId: default
  to: 447455755527@s.whatsapp.net
  body:
    image: 
      url: snapshots/snapshots_camera.camera.jpg
```
