### ISSUE TITLE
line break?

### ISSUE THREAD

**Issue by ear9mrn** [giuseppecastaldo/ha-addons#22]
This is working well. Thanks. Quick question. How do force a new line with a plan text message. tried /n and a few other permutations.

Thanks,

Pete.

**Comment by giuseppecastaldo** [comment]
> This is working well. Thanks. Quick question. How do force a new line with a plan text message. tried /n and a few other permutations.
> 
> Thanks,
> 
> Pete.

Please visit Home Assistant yaml documentation.

**Comment by glmnet** [comment]
```yaml
service: whatsapp.send_message
data:
  clientId: default
  to: ###@s.whatsapp.net
  body:
    text: |-
        Hi it's a simple text message

        It has two lines
```

this can be closed
