### ISSUE TITLE
Buttons and location not sending

### ISSUE THREAD

**Issue by Caldin-Maldin** [giuseppecastaldo/ha-addons#34]
At some point, messages with buttons and location stopped being sent. Only text and photo messages are sent.
There are no errors in HA. Services are processed correctly. In automation, actions are also performed without errors.
HA 2023.6.1

**Comment by Caldin-Maldin** [comment]
I thought the bug would be fixed in the new version, but everything remains the same, messages with location or buttons do not arrive. There are no errors in HA.
Messages with text or photos are received normally.

**Comment by daknightuk** [comment]
I have the location sending working fine but using this example code the Buttons do not work for me: 
service: whatsapp.send_message
data:
  clientId: 449999999999@s.whatsapp.net
  to: 448888888888@s.whatsapp.net
  body:
    text: "Hi it's button message"
    footer: "Hello World"
    buttons:
      - buttonId: "id1"
        buttonText:
          displayText: "Button 1"
        type: 1
      - buttonId: "id2"
        buttonText:
          displayText: "Button 2"
        type: 1
      - buttonId: "id3"
        buttonText:
          displayText: "Button 3"
        type: 1
    headerType: 1

**Comment by cefranco76** [comment]
Any update about button and list messages? Not working for me.

**Comment by jelmerwouters** [comment]
Using the example from the documentation (with correct phone number of course), this still doesn't work for me. Is it supposed to work after the latest update?

```

service: whatsapp.send_message
data:
  clientId: default
  to: 391234567890@s.whatsapp.net
  body:
    text: Hi it's button message
    footer: Hello World
    buttons:
      - buttonId: id1
        buttonText:
          displayText: Button 1
        type: 1
      - buttonId: id2
        buttonText:
          displayText: Button 2
        type: 1
      - buttonId: id3
        buttonText:
          displayText: Button 3
        type: 1
    headerType: 1

```
