### ISSUE TITLE
how i can create new automation?

### ISSUE THREAD

**Issue by moshik132** [giuseppecastaldo/ha-addons#40]
i want to create a new automation but is not work.
the message is not send
You can get an example for building automation

**Comment by XtraLarge** [comment]
Here one of my automations as an example:

```
alias: Neustart per WhatsApp melden
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: whatsapp.send_message
    data:
      clientId: default
      to: 1203631807610852xx@g.us #sending to a group
      body:
        text: HomeAssistant neu gestartet
mode: single
initial_state: "on"

```
