### ISSUE TITLE
Cannot read properties of undefined (reading 'payload')

### ISSUE THREAD

**Issue by sadnblueish** [giuseppecastaldo/ha-addons#41]
On a new install, when sending message with the following service call config:

```
service: whatsapp.send_message
data:
  clientId: default
  to: 92300xxxxxxx@s.whatsapp.net
  body:
    Testing new integration
```
I get following in add-on log:
`[ERROR] default - Cannot read properties of undefined (reading 'payload')`
