### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by benjamin-dcs** [giuseppecastaldo/ha-addons#69]
For some reason [this](https://github.com/giuseppecastaldo/ha-addons/issues/34) issue was closed, but the issue is not resolved. 

Using the example code from the documentation does not result in a message send with buttons. Nothing is received. 

```
service: whatsapp.send_message
data:
  clientId: default
  to: 391234567890@s.whatsapp.net
  body:
    text: Hi it's button message
    footer: Hello World
    buttons:
      - buttonId: id1
        buttonText:
          displayText: Button 1
        type: 1
      - buttonId: id2
        buttonText:
          displayText: Button 2
        type: 1
      - buttonId: id3
        buttonText:
          displayText: Button 3
        type: 1
    headerType: 1
```
