### ISSUE TITLE
React to your own message

### ISSUE THREAD

**Issue by moryoav** [giuseppecastaldo/ha-addons#74]
In whatsapp it's possible to react to your own message. You send a message and then you can add a reaction to that same message you sent. In order to do that with this addon, what I would need is to know the remoteJid generated by "whatsapp.send_message" (because send_message doesn't trigger a "new_whatsapp_message" event, there doesn't seem to be any other way to get the remoteJid of that message). This could be extremely useful. If there's any workaround I'd love to know. 

The simplest solution seems to be to add "response_variable" option to the send_message service.
So that it'll look like this:
```
alias: Send notification
service: whatsapp.send_message
data:
  clientId: default
  to: [my phone number]
  body:
    text: |
      testing
  response_variable: ev
```
Then I could store this variable in a text helper and use it later.
