### ISSUE TITLE
[Feature Request]: How to send value of entity

### ISSUE THREAD

**Issue by ap20132022** [giuseppecastaldo/ha-addons#86]
### The request

how can I send a value or name of an entity (e.g. name of windows/door sensor or value of sun, wind, temperature ?
Thank you very much for your suggest.  

### Is your feature request related to a problem?

```txt
No
```

**Comment by cefranco76** [comment]
action: whatsapp.send_message
data:
  clientId: default
  to: 990012345678@s.whatsapp.net
  body:
    text:  '{{ state_attr("sun.sun", "next_rising") }} '

**Comment by cefranco76** [comment]
```
action: whatsapp.send_message
data:
  clientId: default
  to: 553199999999@s.whatsapp.net
  body:
    text:  'The sun`s next rising will be at {{ state_attr("sun.sun", "next_rising") }} '
```
