### ISSUE TITLE
[Bug]: Camera Proxy API not working

### ISSUE THREAD

**Issue by markushergeth** [giuseppecastaldo/ha-addons#90]
### The problem

When I try to fetch a snapshot from a integrated camera to send it as image via the supervisor api it is not working.

I am using the following code
```
action: whatsapp.send_message
data:
  clientId: default
  to: 49**********@s.whatsapp.net
  body:
    image:
      url: http://supervisor/core/api/camera_proxy/camera.reolink_doorbell_schnappschusse_klar
``` 

The message is not showing up. In the logs of the add on I can only see
```
[2024-09-23T17:24:59.269] [ERROR] default - Cannot read properties of undefined (reading 'payload')
``` 

When I use the send notification option for android smartphone app I have the following yaml
```
action: notify.mobile_app_markus_s23
data:
  data:
    ttl: 0
    priority: high
    image: /api/camera_proxy/camera.reolink_doorbell_schnappschusse_klar
  message: Es hat geklingelt
enabled: true
```
So at least I think the URL should be right according to the [REST API documentation](https://developers.home-assistant.io/docs/api/rest/)

And according to [Supervisor Endpoints](https://developers.home-assistant.io/docs/api/supervisor/endpoints) the add on should have access with this.

Am I dumb and overlook something os is there really a bug with the add on?

### What version of Home Assistant Core has the issue?

2024.9.2

### What version of the addon has the issue?

1.4.1

### What type of installation are you running?

Home Assistant OS

### Log information

```txt
[15:55:27] INFO: Installed custom component.
[2024-09-23T15:55:28.403] [INFO] default - Whatsapp Addon started.
[2024-09-23T15:55:29.541] [INFO] default - default client is ready.
[2024-09-23T16:57:57.752] [ERROR] default - Cannot read properties of undefined (reading 'payload')
[2024-09-23T16:58:23.232] [ERROR] default - Cannot read properties of undefined (reading 'payload')
[2024-09-23T17:13:33.150] [ERROR] default - Cannot read properties of undefined (reading 'payload')
[2024-09-23T17:20:39.394] [ERROR] default - Cannot read properties of undefined (reading 'payload')
[2024-09-23T17:24:59.269] [ERROR] default - Cannot read properties of undefined (reading 'payload')
```

**Comment by CancunManny** [comment]
Hi, not sure if this would help but on action: whatsapp.send_message
```data:
  clientId: default
  to: 49**********@s.whatsapp.net
  body:
    image:
      url: http://supervisor/core/api/camera_proxy/camera.reolink_doorbell_schnappschusse_klar```

I think you need quotation marks around the http url

**Comment by markushergeth** [comment]
Unfortunately the quotation marks did not solve the issue. I think I need to pass with the supervisor token as header. But I have no clue how to do it in the action.

I think the notification is working because it is calling the api directly within home assistant. But the whatsapp send is giving the command in theory to the add on which runs in a container which needs to authenticate first.

But I have no idea how to give the authorization header in the url part of the action.

**Comment by GeoCodeTout** [comment]
Hello @markushergeth 

Did you find a workaround ? 
I would like to send Camera Snapshot via WhatsApp. But I walking around the solution... (exposed folder, Api...)

**Comment by markushergeth** [comment]
Hello @GeoCodeTout 

I found an option with my reolink. The entity has an attribute "access_token".
This token rolls over (i don't know the interval).
With this the container which runs the whatsapp add-on does a simple call to the home assistant api with an valid token and I don't need to use the supervisor api.

```
action: whatsapp.send_message
metadata: {}
data:
  clientId: default
  to: <removed>@g.us
  body:
    image:
      url: >-
        http://homeassistant.local:8123/api/camera_proxy/camera.reolink_doorbell_schnappschusse_klar?token={{
        state_attr('camera.reolink_doorbell_schnappschusse_klar','access_token')
        }}
    caption: 🛎️ Haustür 🚪
```
